name: Deploy Site
run-name: Deploy to Cloudflare by @${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "staging"

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    environment:
      name: ${{ vars.ENVIRONMENT_NAME }}
      url: ${{ vars.DEPLOYMENT_URL }}
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Build with Vite
        run: yarn run ${{ vars.BUILD_COMMAND }}
      - name: Deploy with Wrangler
        run: yarn run deploy
