name: Deploy Site
run-name: Deploy to Cloudflare by @${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "staging"

env:
  STAGE_URL: "https://stage.noahger.sh/"
  PROD_URL: "https://noahger.sh/"

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
      url: ${{ github.ref_name == 'main' && env.PROD_URL || env.STAGE_URL}}
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Build with Vite
        run: yarn run ${{ vars.BUILD_COMMAND }}
      - name: Deploy with Wrangler
        run: yarn run deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
